version: "3.8"
services:
  app:
    build: .
    ports:
      - "80:3000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: cafe_u
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cafe_d
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata: