version: "3.8"
services:
  app:
    build: .
    ports:
      - "80:3000"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: postgres:16
    env_file:
      - .env
    environment:
      - POSTGRES_USER= ${POSTGRES_USER}
      - POSTGRES_PASSWORD= ${POSTGRES_PASSWORD}
      - POSTGRES_DB= ${POSTGRES_DB}
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/postgresql/data

volumes:
  dbdata: